framework:
    messenger:
        buses:
            messenger.bus.async:
                default_middleware:

        transports:
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    table_name: messenger_messages
                retry_strategy:
                    max_retries: 5
                    delay: 1000
                    multiplier: 2
                    max_delay: 5000
                failure_transport: failed
            failed:
                dsn: "%env(FAILED_MESSENGER_TRANSPORT_DSN)%"
                options:
                    table_name: failed_messages
        routing:
            'App\Message\FileConversionMessage': async

        failure_transport: failed
